# Generated by Django 4.0.4 on 2022-06-18 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BlogProjecr',
            new_name='BlogProject',
        ),
    ]
