# Generated by Django 4.0.4 on 2022-06-18 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_rename_blogprojecr_blogproject'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogproject',
            old_name='data',
            new_name='date',
        ),
    ]
